[2024-06-06T22:38:24.601+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-06T22:38:24.659+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline_v2.handle_comments manual__2024-06-06T22:38:10.830526+00:00 [queued]>
[2024-06-06T22:38:24.678+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline_v2.handle_comments manual__2024-06-06T22:38:10.830526+00:00 [queued]>
[2024-06-06T22:38:24.680+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-06T22:38:24.717+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): handle_comments> on 2024-06-06 22:38:10.830526+00:00
[2024-06-06T22:38:24.735+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=169) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-06T22:38:24.740+0000] {standard_task_runner.py:63} INFO - Started process 171 to run task
[2024-06-06T22:38:24.739+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline_v2', 'handle_comments', 'manual__2024-06-06T22:38:10.830526+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpakny771g']
[2024-06-06T22:38:24.743+0000] {standard_task_runner.py:91} INFO - Job 59: Subtask handle_comments
[2024-06-06T22:38:24.770+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-06-06T22:38:24.849+0000] {task_command.py:426} INFO - Running <TaskInstance: data_pipeline_v2.handle_comments manual__2024-06-06T22:38:10.830526+00:00 [running]> on host be153ff008c0
[2024-06-06T22:38:25.174+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sanket' AIRFLOW_CTX_DAG_ID='data_pipeline_v2' AIRFLOW_CTX_TASK_ID='handle_comments' AIRFLOW_CTX_EXECUTION_DATE='2024-06-06T22:38:10.830526+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-06T22:38:10.830526+00:00'
[2024-06-06T22:38:25.184+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-06T22:38:25.187+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-06T22:38:25.190+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/src/data_preprocessing/handle_comments.py", line 11, in remove_comments
    for item in data:
TypeError: 'bool' object is not iterable
[2024-06-06T22:38:25.229+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=data_pipeline_v2, task_id=handle_comments, run_id=manual__2024-06-06T22:38:10.830526+00:00, execution_date=20240606T223810, start_date=20240606T223824, end_date=20240606T223825
[2024-06-06T22:38:25.277+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 59 for task handle_comments ('bool' object is not iterable; 171)
[2024-06-06T22:38:25.320+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-06T22:38:25.354+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
